spring:
  application:
    name: comentarios-service

  data:
    mongodb:
      uri: "mongodb://jaredpimente1_db_user:DpCito170209@cluster0-shard-00-00.cibvezm.mongodb.net:27017,cluster0-shard-00-01.cibvezm.mongodb.net:27017,cluster0-shard-00-02.cibvezm.mongodb.net:27017/enseniamelo?ssl=true&replicaSet=atlas-abcdef-shard-0&authSource=admin&retryWrites=true&w=majority"

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/enseniamelo-realm/protocol/openid-connect/certs

  cloud:
    stream:
      bindings:
        comentarioCreado-out-0:
          destination: comentarios
          content-type: application/json
        comentarioEliminado-out-0:
          destination: comentarios
          content-type: application/json
