spring:
  application:
    name: comentarios-service

  data:
    mongodb:
      uri: "{cipher}ed952b47800a9a59c4aadf2cac3c9ee10e0ec54aa401cd78e043fc12370b7a6a"

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/enseniamelo-realm/protocol/openid-connect/certs

  cloud:
    stream:
      bindings:
        comentarioCreado-out-0:
          destination: comentarios
          content-type: application/json
        comentarioEliminado-out-0:
          destination: comentarios
          content-type: application/json
