spring:
  application:
    name: gateway-service

  security:
    oauth2:
      resourceserver:
        jwt:
          # Dentro de Docker:
          jwk-set-uri: http://keycloak:8080/realms/enseniamelo-realm/protocol/openid-connect/certs
      # (Opcional) Si también usas OAuth2 Client (login), define registration/provider,
      # pero para repo público usa variables o {cipher} para el client-secret.

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        # Documentación Usuarios (pública)
        - id: usuarios-openapi-swagger-ui
          uri: lb://usuarios-service
          predicates:
            - Path=/usuarios/openapi/**
          filters:
            - RewritePath=/usuarios/openapi(?<segment>.*), /openapi${segment}
            - RemoveRequestHeader=Authorization
          order: -1

        # Documentación Comentarios (pública)
        - id: comentarios-openapi-swagger-ui
          uri: lb://comentarios-service
          predicates:
            - Path=/comentarios/openapi/**
          filters:
            - RewritePath=/comentarios/openapi(?<segment>.*), /openapi${segment}
            - RemoveRequestHeader=Authorization
          order: -1

        # Auth público
        - id: auth-api-public
          uri: lb://usuarios-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=/api(?<segment>.*), ${segment}
            - RemoveRequestHeader=Authorization
          order: 0

        # Comentarios - GET público
        - id: comentarios-api-public-get
          uri: lb://comentarios-service
          predicates:
            - Path=/api/comentario-curso,/api/comentario-curso/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Authorization
          order: 0

        # Comentarios - Mutaciones protegidas (Authorization se reenvía)
        - id: comentarios-api-secured-mutate
          uri: lb://comentarios-service
          predicates:
            - Path=/api/comentario-curso,/api/comentario-curso/**
            - Method=POST,PUT,DELETE
          order: 0

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:4200"
              - "http://localhost:5173"
              - "http://localhost:8080"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders:
              - Authorization
            allowCredentials: true
            maxAge: 3600

eureka:
  instance:
    hostname: gateway-service

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.security: INFO