server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore/keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: gateway

spring:
  application:
    name: gateway-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/enseniamelo-realm

  cloud:
    gateway:
      default-filters:
        - TokenRelay

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: ms-usuarios
          uri: lb://usuarios-service
          predicates:
            - Path=/ms-usuarios/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Forwarded-Prefix, /ms-usuarios
            - AddRequestHeader=X-Forwarded-Proto, http
          order: 1

        # -------- DOCUMENTACIÓN (Swagger / OpenAPI) -------------
        - id: usuarios-docs
          uri: lb://usuarios-service
          predicates:
            - Path=/usuarios/docs,/usuarios/swagger,/usuarios/openapi,/usuarios/openapi/**
          filters:
            - StripPrefix=1
          order: 1

        - id: ms-payments
          uri: lb://payments-service
          predicates:
            - Path=/ms-payments/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Forwarded-Prefix, /ms-payments
            - AddRequestHeader=X-Forwarded-Proto, http
          order: 1

        - id: payments-docs
          uri: lb://payments-service
          predicates:
            - Path=/payments/docs
          filters:
            - StripPrefix=1
          order: 2

        - id: payments-redoc
          uri: lb://payments-service
          predicates:
            - Path=/payments/redoc
          filters:
            - StripPrefix=1
          order: 2

        - id: payments-openapi
          uri: lb://payments-service
          predicates:
            - Path=/payments/openapi.json
          filters:
            - StripPrefix=1
          order: 2

        - id: openapi-root-to-payments
          uri: lb://payments-service
          predicates:
            - Path=/openapi.json
          order: 0

        - id: eureka-web-start
          uri: http://eureka-server:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
          order: 2

        - id: eureka-web-other
          uri: http://eureka-server:8761
          predicates:
            - Path=/eureka/**
          order: 2


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    preferIpAddress: true
    hostname: gateway-service
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 8443

management:
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    "[org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator]": INFO
    "[org.springframework.cloud.gateway]": DEBUG
    "[org.springframework.security]": DEBUG
    "[org.springframework.security.oauth2]": DEBUG
