server.port: 8443
server.ssl:
  enabled: true
  key-store: classpath:keystore/keystore.p12
  key-store-password: changeit
  key-store-type: PKCS12
  key-alias: gateway
spring:
  application:
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8080/realms/enseniamelo
            jwk-set-uri: http://keycloak:8080/realms/enseniamelo/protocol/openid-connect/certs

  cloud:
    gateway:
      default-filters:
        - TokenRelay

      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

      routes:
        # ===================== SWAGGER MENSAJES SERVICE =====================

        # Swagger UI HTML + recursos estáticos
        - id: mensajes-swagger-ui
          uri: lb://mensajes-service
          predicates:
            - Path=/mensajes/swagger-ui.html,/mensajes/swagger-ui/**,/mensajes/webjars/**,/mensajes/openapi/swagger-ui/**
          filters:
            - RewritePath=/mensajes/(?<remaining>.*), /$\{remaining}
          order: 1

        # OpenAPI JSON docs
        - id: mensajes-openapi-docs
          uri: lb://mensajes-service
          predicates:
            - Path=/mensajes/openapi/v3/api-docs,/mensajes/openapi/v3/api-docs/**
          filters:
            - RewritePath=/mensajes/(?<remaining>.*), /$\{remaining}
          order: 1

        # ===================== EUREKA SERVER =====================
        # Eureka Dashboard (acceso a través del gateway)
        - id: eureka-web
          uri: http://eureka-server:8761/eureka/
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        # Eureka API
        - id: eureka-api
          uri: http://eureka-server:8761/eureka/
          predicates:
            - Path=/eureka/**

        # ============ RUTAS MENSAJES SERVICE ============

        - id: mensajes-v1-direct
          uri: lb://mensajes-service
          predicates:
            - Path=/v1/mensaje,/v1/mensaje/**
          order: 1

        - id: mensajes-v1-api
          uri: lb://mensajes-service
          predicates:
            - Path=/api/v1/mensaje,/api/v1/mensaje/**
          filters:
            - RewritePath=/api/v1/(?<segment>.*), /api/${segment}
          order: 1

        - id: chats-v1-direct
          uri: lb://mensajes-service
          predicates:
            - Path=/v1/chat,/v1/chat/**
          order: 1

        - id: chats-v1-api
          uri: lb://mensajes-service
          predicates:
            - Path=/api/v1/chat,/api/v1/chat/**
          filters:
            - RewritePath=/api/v1/(?<segment>.*), /api/${segment}
          order: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    preferIpAddress: false
    hostname: gateway-service
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 8443

management:
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    "[org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator]": INFO
    "[org.springframework.cloud.gateway]": DEBUG
    "[org.springframework.security]": DEBUG
    "[org.springframework.security.oauth2]": DEBUG
