spring:
  application:
    name: mensajes-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:9090/realms/enseniamelo
          jwk-set-uri: http://keycloak:9090/realms/enseniamelo/protocol/openid-connect/certs

server:
  port: 8082
  forward-headers-strategy: framework

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
  instance:
    hostname: mensajes-service
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    mongo:
      enabled: true

logging:
  level:
    root: INFO
    "[com.enseniamelo]": DEBUG
    "[org.springframework.security]": DEBUG
    "[com.netflix.discovery]": DEBUG
    "[com.netflix.eureka]": DEBUG