spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/enseniamelo
          jwk-set-uri: http://mykeycloak:8080/realms/enseniamelo/protocol/openid-connect/certs

server:
  port: 8082
  forward-headers-strategy: framework

logging:
  level:
    root: INFO
    "[bo.edu.ucb.microservices]": DEBUG
    "[org.springframework.security]": DEBUG

spring.config.activate.on-profile: docker
server.port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,bindings,env
  endpoint:
    health:
      show-details: always
  health:
    mongo:
      enabled: true
